DefaultContentLanguage = "fr"
baseurl = "https://kakesa.net/"
languageCode = "fr-fr"
title = "Christian Kakesa, Le Blog"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = "shortname"
googleAnalytics = "UA-1496206-2"
pluralizeListTitles = false

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "La passion de la tech."
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Christian Kakesa"
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"

# Optional Params
    # This will match the navbarTitle to the section of the website
    dynamicTitles        = true
    # RSS icon that appear on the sidebar, next to the social media buttons
    rssAppearAtTop       = true
    rssAppearAtBottom    = true
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = true
    faviconVersion       = ""

    # Disable showing the social sharing links on blog posts
    socialShareDisabled = true

    # Load custom CSS or JavaScript files. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    customCSS            = ["default"]
    customJS             = ["default"]

# Disqus will take priority over staticman due to its ease of use. Feel free to check out both and decide.
[params.staticman]
    staticman = false
    username  = ""
    repo      = ""
    branch    = ""

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Le Blog de Christian Kakesa"

    paragraph = "Bienvenue sur mon blog <i class=\"fa fa-hand-peace-o\"></i> !"

    about     = ""

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "https://pbs.twimg.com/profile_images/911693574143651842/op-PeJSR_400x400.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "Photo de Christian Kakesa"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    identifier = "fa fa-newspaper-o"
    weight = 1

# [[menu.main]]
#     name = "Itemized"
#     url = "/itemized/"
#     identifier = "fa fa-list"
#     weight = 999

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    identifier = "fa fa-sitemap"
    weight = 2

[[menu.main]]
    name = "Infos"
    url = "/infos/"
    identifier = "fa fa-id-card-o"
    weight = 3

# [[menu.main]]
#     name = "Contact"
#     url = "/contact/"
#     identifier = "fa fa-envelope-o"
#     weight = 999

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "fenicks"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "christiankakesa"
    slideshare      = ""
    stackoverflow   = "592319/christian-kakesa?tab=profile"
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "christiankakesa"
    email           = ""
